enableGlobalCache: true

logFilters:
  - code: YN0032
    level: discard

nodeLinker: node-modules

packageExtensions:
  react-dev-utils@*:
    peerDependencies:
      typescript: ^4.0.1
      webpack: ^5.60.0
    peerDependenciesMeta:
      typescript:
        optional: true
  react-native-codegen@*:
    peerDependencies:
      "@babel/preset-env": ^7.1.6
  react-native@*:
    peerDependencies:
      "@babel/preset-env": ^7.1.6

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
